spring:
    redis:
        database: 1
        host: localhost
        port: 6379
        pool:
            max-active: 20

    rabbitmq:
        host: 192.168.56.105
        port:  5672
        username: cwh
        password: 123456